Tests/Resources/enterprise-production.xml
Tests/Resources/enterprise-sandbox.xml
Tests/Source/ZMMobileProvisionParserTests.m
Tests/appstore-sandbox.xml
ZMUtilities.xcodeproj/project.pbxproj

**What's in this PR?**
The tests for `ZMMobileProvisionParser` were failing as the provisioning profiles were missing.
This PR adds sanitized profiles in XML format and creates binary plists in the tests using these fixtures.

Add sanitized provisioning profiles to fix tests

---

Source/Public/OptionalComparison.swift
Tests/OptionalComparisonTests.swift
ZMUtilities.xcodeproj/project.pbxproj

* This add the comparison operator definitions for optionals inserted by the Swift 3 migrator, as we would otherwise add them to multiple other projects.

Add optional comparison operators

---

Source/Public/Dictionary.swift
Source/Public/Sets.swift
Tests/DictionaryTests.swift
ZMUtilities.xcodeproj/project.pbxproj

Add function to create a dictionary from a sequence. This is useful in those many places when we want to create a look up table from an array to avoid iterating the entire array to find element by id many times over.
E.g. when fetching a bunch of results from Core Data in a single fetch, then I want to access them by their ID

Add function to create a dictionary from a sequence

---

Source/Public/String+Emoji.swift
Tests/String+EmojiTests.swift
ZMUtilities.xcodeproj/project.pbxproj

Add an extension on String to check for Emoji, this is needed in order to disallow the input of emoji as username, as a check like
```swift
let allowed = CharacterSet(charactersIn: "abcdefghijklmnopqrstuvwxyz_").union(.decimalDigits)
CharacterSet(charactersIn: handle).isSubset(of: allowed)
```
will not catch emoji.

Add extension on String to detect Emoji

---

Source/Public/Dictionary.swift
Tests/DictionaryTests.swift

Adds three new functions:
1) Mapping a dictionaries keys and values to a new dictionary
2) Initializing a Dictionary with an array of keys and setting the same value for each key
3) Updating and merging a dictionaries values with another dictionary

Add functions for mapping dictionaries 

---

Source/Public/NSPredicateOperators.swift
Tests/NSPredicateOperatorTests.swift
ZMUtilities.xcodeproj/project.pbxproj

* Custom operators 😱.
* Add convenience operators to create a compound `NSPredicate` out of two subpredicates using `&&` or `||`.

Add NSPredicate compounding operators

---

Source/NSString+Normalization.m
Tests/Source/NSString_NormalizationTests.m

* There were issues when searching in non-latin languages , e.g. in Chinese multiple signs can have the same transliteration, which means all of them will be matched in a search when searching for any of them. In order to avoid these issues no transliteration to latin should happen during the normalization (so only lowercasing and striping diacritics).

Revert transliterating to latin in search normalization

---

Source/Public/Optional+Apply.swift
Tests/Optional+ApplyTests.swift
WireUtilities.xcodeproj/project.pbxproj

Add `Optional.apply` function to perform side effects (instead of misusing `map` to do so). 
This function should be used to execute a code block only if the caller is non-nil.  
```swift
// Considering we have the following:
func foo(_ bar: Int) {
NotificationCenter.default.post(name: .FooNotification, object: bar)
}
// Instead of this:
if let bar = optionalBar {
foo(bar)
}
// You can now write this:
optionalBar.apply(foo)
```

Add apply function

---

Source/FileManager+Protection.swift

During automation we noticed that app crashes when installing on iOS11 simulator. It crashes because FileManager fails to create a directory:
```
fatal error: Failed to create directory: file:///<EDITED>/data/Containers/Shared/AppGroup/<APP_ID>/AccountData/<ACCOUNT_ID>/sharedObjectStore/, 
error: Error Domain=NSCocoaErrorDomain Code=512 "The file “AccountData” couldn’t be saved in the folder “<APP_ID>”." 
UserInfo={NSFilePath=<EDITED>/data/Containers/Shared/AppGroup/<APP_ID>/AccountData, 
NSUnderlyingError=0x6040002467e0 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}}: 
file /Users/jenkins/Desktop/jenkins-agent/workspace/Utility jobs/Create a new version of framework/Source/ZMSAsserts.swift, line 26
```
The underlying reason is unclear as the directory structure before the …

Fix: crash when installing on iOS 11 simulator.

---

Source/FileManager+FileProtectionLock.swift
Source/NSData+ZMSCrypto.m
Source/NSUserDefaults+SharedUserDefaults.m
Tests/Source/ZMEncodedNSUUIDWithTimestampTests.m

As reported by Raphael, `success == 0` should be changed to `success == errSecSuccess`.
I replaced `success == 0` with `success == errSecSuccess` on these files:
- `NSData+ZMSCrypto.m`
- `NSUserDefaults+SharedUserDefaults.m`
- `ZMEncodedNSUUIDWithTimestampTests.m`

ZIOS-9243: Pseudorandom Generator improvement

---

Source/Validation/ZMStringLengthValidator.m
Tests/Source/Validation/ZMStringLengthValidatorTests.m
Tests/String+ExtremeCombiningCharactersTests.swift

* Don't replace zero width joiner (U+200D) with spaces in string length validation

Don't replace zero width joiner with spaces in string validation

---

Source/FixedWidthInteger+Random.swift
Source/UInt+Random.swift
Tests/FixedWidthInteger_RandomTests.swift
WireUtilities.xcodeproj/project.pbxproj

`secureRandomNumberWithUpperBound` was not visible in Objective-C, since `uint32_t` is a primitive type.
I've added a bridge that does the same thing using `NSNumber` as the base class for the static method. Not the most elegant solution, I know - suggestions are welcome!

Added support for secure random number generation on ObjC

---

Source/Result.swift
Tests/ResultTests.swift
WireUtilities.xcodeproj/project.pbxproj

* Add a simple result enum type including helper accessors and `map` implementation.
* It would be nice to add a `flatMap` function at some point to avoid `Result<Result<T>>` types.

Add a simple result enum type

---

Source/Composition.swift
Source/Result.swift
Tests/ResultTests.swift
WireUtilities.xcodeproj/project.pbxproj

Nice functional utility: binary operator that takes 2 functions and composes the new function from them:
`(f1 ∘ f2)(x) = f1(f2(x))`
Usage example: https://github.com/wireapp/wire-ios-sync-engine/pull/731/files

Basic one-way function composition

---

Source/NSmanagedObjectContext+PerformGrouped.swift

* Allow throwing functions inside a `performGroupedBlockedAndWait` block.

Allow throwing functions inside a performAndWait block

---

Source/Public/TearDownCapable.swift
WireUtilities.xcodeproj/project.pbxproj

`tearDown` is a common method that gets implemented in various places throughout the codebase. Sometimes we need to tear down objects stored in untyped arrays and it's useful to just check if they implement `TearDownCapable` protocol and call the method on it.

Added protocol for tearing down objects

---

Source/Public/FunctionOperators.swift
Tests/FunctionOperatorTests.swift
WireUtilities.xcodeproj/project.pbxproj

This operator can be used to negate a boolean test function, e.g. `streams.filter(!streamIds.contains)` instead of  `streams.filter { !streamIds.contains($0) }`.

Add prefix operator to flip a boolean test function

---

Source/Public/Equatable+OneOf.swift
Tests/Equatable+OneOfTests.swift
WireUtilities.xcodeproj/project.pbxproj

**Add helper method to check for containment, works with variadic arguments or any collection type.**
Instead of
```swift 
[42, 43, 65].contains(interestingValue)
```
I find this to be more readable
```swift 
interestingValue.isOne(of: 42, 54, 65)
```

 Add helper method to check for containment

---

Source/Public/Map+KeyPath.swift
Tests/MapKeyPathTests.swift
WireUtilities.xcodeproj/project.pbxproj

We add convenience methods that allow us to map/flatMap/compactMap/filter properties in sequences and optional values by using key paths, instead of having to use a closure.
***Before***
~~~swift
let names: [String] = people.map { $0.name }
~~~
***After***
~~~swift
let names: [String] = people.map(\.name)
~~~
***Before***
~~~swift
let age: Int? = optionalPerson.flatMap { $0.age }
~~~
***After***
~~~swift
let age: Int? = optionalPerson.flatMap(\.age)
~~~

Add methods to map sequences/optionals with key path

---

Source/Result.swift
Tests/ResultTests.swift

* Add init to create a VoidResult from an optional Error.

Add init to create a VoidResult from an optional Error

---

Source/Public/ZMEmailAddressValidator.h
Source/Public/ZMPhoneNumberValidator.h
Source/Validation/ZMEmailAddressValidator.m
Source/Validation/ZMPhoneNumberValidator.m
Tests/Source/Validation/ZMEmailAddressValidatorTests.m
Tests/Source/Validation/ZMPhoneNumberValidatorTests.m

The phone number and email validators take a reference to an NSString pointer to check the validity of user input, and change the string when it can normalize it. 
While this may be useful in some cases, this API can be harder to use when we just want to check if text is valid without checking the updated value; especially in Swift where it is imported with an odd signature that does not return a Boolean value:
~~~swift
class func validateEmailAddress(_ ioEmailAddress: AutoreleasingUnsafeMutablePointer<NSString?>?) throws
~~~
For example, to check if an e-mail is valid, we'd need to write:
~~~swift
func isValidEmail(_ email: String?) -> Bool {
var validationEmail: NSString? = email as NSString?
do {
try ZMEmailAddressValidator.validateEmailAddress(&validationEmail)
} catch {
return false …

Add non-mutable validators for better Swift import

---

Source/NSString+Normalization.m
Source/Public/NSString+Normalization.h
Tests/Source/NSString_NormalizationTests.m

When searching users for creating a mention, we need to normalise the search strings but keep the punctuation. The existing method for normalising search strings removes punctuation after normalisation.

Add method to normalize string for mention search

---

Source/FileManager+FileProtectionLock.swift

We are seeing crashes in `isFileSystemAccessible` with `EXC_BREAKPOINT trap 5`. This is indication the system intentionally crashes due to a broken precondition (Force unwrap, unexpected nil).
https://rink.hockeyapp.net/manage/apps/42908/app_versions/1099/crash_reasons/243642663
It's not clear from the stack trace exactly which line causes the crash but we do some force unwraps in that method.
Remove force unwraps.

Avoid force unwraps when checking if the file system is readable

---

Source/Public/String+Emoji.swift
Source/Validation/ZMPhoneNumberValidator.m
Tests/EmojiOnlyStringTests.swift
Tests/String+EmojiTests.swift
WireUtilities.xcodeproj/project.pbxproj

Move the emoji String extension from Wire-iOS (https://github.com/wireapp/wire-ios/pull/2787).
String.containsEmoji method is merged with revised logic and more test case for unicode 11.0 and ancient language are added.

improve emoji detection logic and add test cases

---

WireUtilities.xcodeproj/project.pbxproj

Fix the invalid target of EmojiOnlyStringTests.

fix: invalid target of EmojiOnlyStringTests

---

Source/Public/String+Emoji.swift
Source/Public/StringLengthValidator.swift
Tests/EmojiOnlyStringTests.swift
Tests/Source/Validation/StringLengthValidator.swift
Tests/Source/Validation/StringLengthValidatorTests.swift
WireUtilities.xcodeproj/project.pbxproj

Self-profile screen: username with Wales flag is shown as black flag and spaces
StringLengthValidator replaces all Unicode 5.0 Tags with spaces, which are part of a complete emoji.
Check every Character in the String is an emoji and not a character in controlSet.

Fix: Self profile screen: user name with Wales flag is shown as black flag and spaces

---

Source/Public/ZMTimer.h
Source/ZMTimer.m

Clients of the timer were not able to access its state. While this fits most scenarios, we need to be able to access the state of the timer when it is used inside expiring background tasks.
Typically, when the background task that accesses the timer expires, we need to act like the timer fired, and cancel it if it is running. For example, we might need to do something like this:
~~~swift
class BackgroundRequestTimer {
let timer = ZMTimer(target: self)
func start() {
let activity = BackgroundActivityFactory.shared.beginBackgroundActivity()
activity?.expirationHandler = self.finish
if activity != nil {
self.timer.start()
} else {
finish()
}
}
func timerFired(_ timer: ZMTimer) {
self.finish()
}
func finish() {
if timer.state == .running {
timer.cancel()
}
Network.cancelRequests()
}
}
~~~
In …

Expose state of ZMTimer publicly

---

Source/Array+PartitionByKeyPath.swift
Tests/ArrayPartitionByKeyPathTests.swift
WireUtilities.xcodeproj/project.pbxproj

Add helper method for partitioning an Array by key path. This will help us to partition an array of messages by their sender.

Add helper method for partitioning an Array by key path

---

Source/Array+SafeIndex.swift
Tests/ArraySafeIndexTests.swift
WireUtilities.xcodeproj/project.pbxproj

We add the `element(atIndex:)` utility on the collection protocol to be able to return an optional when accessing the index of the array, instead of having to check the start and end index or count manually.
**Before**
~~~swift
func getSecondItem(in array: [String]) -> String? {
guard array.count >= 2 else { return nil }
return array[1]
}
~~~
**After**
~~~swift
func getSecondItem(in array: [String]) -> String? {
return array.element(atIndex: 1)
}
~~~

Add collection extension for safe indexing

---

Source/Password/PasswordCharacterClass.swift
Source/Password/PasswordRuleSet.swift
Source/Password/PasswordValidationResult.swift
Source/Public/String+Emoji.swift
Tests/PasswordRuleSetTests.swift
Tests/Source/UnownedNSObjectTests.swift
WireUtilities.xcodeproj/project.pbxproj
WireUtilities.xcodeproj/xcshareddata/xcschemes/WireUtilities.xcscheme

We want to introduce password validation rules that can:
1. Be customized
2. Validate the length of the password
3. Validate that the password does not contain disallowed characters
4. Validate that the password contains at least one of each specified character classes
We introduce a new `PasswordRuleSet` object. This object contains all the properties required to validate a password. It can be created from a JSON object to allow clients to customize it in the Configuration file.
This is an example JSON that represents password rules:
```json
{
"minimum-length": 8,
"maximum-length": 120,
"allowed-characters": [
"ascii-printable",
],
"required-characters": [
"digits",
"[🐼]"
]
}
```
The first two parameters are `minimumLength` and `maximumLength`. They are unsigned integers that are used to …

ZIOS-11350: Implement password validation rules

---

Source/Password/PasswordCharacterClass.swift
Source/Password/PasswordRuleSet.swift
Source/Public/String+Emoji.swift
Tests/PasswordRuleSetTests.swift

We need to update the password rules the after some discussions related to the spec this morning:
- Update the Unicode character class to include all scalars
- Update the uppercase/lowercase character class to include only ASCII
- Update the special character class to include all non ASCII lowercase/uppercase/digits
- Update the JSON keys of the rule set structure
This will require an update of the build configuration.

ZIOS-11350: Update password rules for new spec

---

Source/Public/Data+ReadableHash.swift
Source/Public/String+ReadableHash.swift
Source/Public/UUID+Data.swift
WireUtilities.xcodeproj/project.pbxproj

We sometimes want to anonymise a string while keeping the possibility to compare them, e.g. user identifiers in logs.
We hash the string with SHA256 and trim to 8 characters which makes it somewhat readable while still avoiding duplicates.

Added readable hash for strings

---

Source/Public/WireUtilities.h
Source/Public/ZMObjectValidationError.h
Source/Validation/ZMPropertyValidator.swift
Source/ZMObjectValidationError.m
WireUtilities.xcodeproj/project.pbxproj

Wrong error message for too long account name
Auto generated wrong error domain constant
Created a objetiveC class named ZMObjectValidationError and expose a const for the error domain string.
https://github.com/wireapp/wire-ios/pull/4176

[Fix]: Wrong error message for username too long.

---

Tests/Source/UnownedObjectTests.swift

After upgraded to Xcode 11, `testThatUnownedObjectIsInvalidIfValueDoesNotExistAnymore` fails.
`Date` is no longer a object in Xcode 11 and not suitable for testing `UnownedObject `
Replace it with `NSObject`

fix: failed testThatUnownedObjectIsInvalidIfValueDoesNotExistAnymore

---

Source/Public/NSManagedObjectContext+WireUtilities.h

Add `nonnull` markers to `executeFetchRequestOrAssert`, copied from https://github.com/wireapp/wire-ios-data-model/pull/1055
For other methods in the header, add `_Null_unspecified` markers for now

[Chore] Add non null and null_unspecified

---

Source/Keychain/Keychain+Passcode.swift
Source/Keychain/PasscodeKeychainItem.swift
WireUtilities.xcodeproj/project.pbxproj

Move the `Keychain` extension from the UI because we need it in the Data Model.
- **Why do we need it in the Data Model?**
There is a new protocol `ApplockType` which contains a `isCustomPasscodeNotSet` property.  We need a method to fetch the passcode from the `Keychain`.
```
var isCustomPasscodeNotSet: Bool {
return config.useCustomCodeInsteadOfAccountPassword && Keychain.fetchPasscode() == nil
}
```
https://github.com/wireapp/wire-ios-data-model/pull/1081

[Refactor] Add Keychain extension for the fetching passcode

---

Source/Public/UTType.swift
Source/UTIHelper.swift
Tests/UTIHelperTests.swift
WireUtilities.xcodeproj/project.pbxproj

Create `UTIHelper` to replace deprecated `UTTypeConformsTo` and `UTTypeCopyPreferredTagWithClass` method
remove `UTType` struct after iOS 13 is dropped.

UTI Helper

---

Source/Public/Data+Image.swift
Tests/NSData+ImageTests.swift

Retire `ZMAssetMetaDataEncoder` form images which uses deprecated method and refactor as `Data.mimetype`

data mimetype helper

---

Source/UTIHelper.swift
Tests/UTIHelperTests.swift

Add support of `quicktime` as movie type for `conformsToMovieType` method.
Add support of `m4a` and `mp4` as audio type for `conformsToMovieType` method.

Fix: support more UTI types for movie and audio 
